config/routes.rb
Rails.application.routes.draw do
  get 'games/new'
  get 'users/new'
  resources :users
  resources :games
  resources :sessions, only: [:new, :create, :destroy]
  root 'static_pages#home'
  match '/twitter-signin', to: 'users#twitter_signin', via: 'get'
  match '/browse', to: 'games#index', via: 'get'
  match '/upload', to: 'games#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete' 
  match '/signup', to: 'users#new', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
     <h4><%= link_to "GTN", root_path, { :class => "signin_link", :style => "color: black" } %></h4>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse bottom-shadow" id="nav">
  <div class="navbar-inner">
    <div class="container">
      <div class="row" >
        <div class="col-xs-1 col-md-4">
          <h4 style="padding-top: 5px;"><%= link_to "GTN", root_path, { :class => "signin_link" } %></h4>
        </div>
        <div class="col-xs-10 col-md-8">
          <nav>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Browse",    browse_path %></li>
              <li><%= link_to "Leaderboard",    users_path %></li>
              <li><%= link_to "Help",  help_path %><li>
            
	      <li style="padding-top: 10px; padding-left: 15px"><button type="button" class="btn btn-success">
		    <%= link_to "Sell Game", upload_path, {:class => "signin_link" } %>
		    <span class="glyphicon glyphicon-cloud-upload"></span>
		    </button>
              </li>
               
               <% if signed_in? %>
              <li style="padding-left: 20px">
	       
                  <div class="btn-group" style="padding-top: 10px;">
                      <button type="button" class="btn btn-success">
                         <span class="glyphicon glyphicon-wrench"></span>
                         <%= link_to " Account", current_user, { :class => "signin_link" } %>
                      <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
                        <span class="caret"></span>
                        <span class="sr-only">Toggle Dropdown</span>
                      </button>
                      <ul class="dropdown-menu" role="menu">
                        <li><%= link_to "Profile", current_user %></li>
                        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                        <li class="divider"></li>
                        <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
                      </ul>
                    </div>
                  </li>
                <% else %>
                   <li style="padding-top: 10px; padding-left: 15px"><button type="button" class="btn btn-primary">
        <%= link_to "Sign Up", signup_path, {:class => "signin_link" } %>
        </button>
              </li>
               <li style="padding-top: 10px; padding-left: 15px"><button type="button" class="btn btn-success">
        <%= link_to "Sign In", signin_path, {:class => "signin_link" } %>
        </button>
              </li>

                <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <% render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <div class="container">
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
      </div>
  </body>
</html>